apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpine
  name: alpine-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - args:
        - sh
        - -c
        - sleep 600
        image: alpine
        name: alpine
